package:
    name: call_map
    version: 0.1.0

source:
    git_rev: master
    git_url: bb:andylee-work/call_map

requirements:
    build: 
        - python
        - setuptools

        - pyqt
        - toolz
        - qtconsole
        - pygments
        - jedi ==0.10.0

    run:
        - python
        - pyqt
        - toolz
        - qtconsole
        - pygments
        - jedi ==0.10.0

test:
    imports:

about:
    home:
    license:
    license_file:

